language: java

jdk:
  - openjdk8

# prevent travis running gradle assemble; let the build script do it anyway
install: true

sudo: required # faster builds
  
script: "mvn clean test cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
